package pe.com.vical.examplevaadin.ui.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class GridComponentDesign extends CssLayout{
	protected VerticalLayout lytContenido;
	protected TextField txtNombre;
	
	public GridComponentDesign(){
		Design.read(this);
	}
}
