package pe.com.vical.examplevaadin.ui.desing;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class LoginDesign extends VerticalLayout {
	protected Panel pnlLogin;
	protected VerticalLayout lytLogin;
	protected Image imgIcono;
	protected HorizontalLayout lytUsuario;
	protected Label lblUsuario;
	protected TextField txtUsuario;
	protected HorizontalLayout lytPassword;
	protected Label lblPassword;
	protected PasswordField txtPassword;
	protected HorizontalLayout lytAccion;
	protected Button btnIngresar;

	public LoginDesign() {
		Design.read(this);
	}
}
